### ISSUE TITLE
MINOR FIX: Source Acceptance Get Test Fix

### ISSUE THREAD

**Issue by glhays** [The-Standard-Organization/GitFyle.Core.Api#315]

**Comment by glhays** [comment]
Resolved or unnecessary.

**Comment by glhays** [comment]
@SlimAhmad 
Just pulled latest.. Can you elaborate on why you re-opened the issue?

![Image](https://github.com/user-attachments/assets/a290da83-ae3c-4965-9d27-c33ab43df31f)

**Comment by SlimAhmad** [comment]
@glhays hi  Greg,for some reasons the get all sources fails sometimes when I push a commit and when i rerun the build job it works. I just reopened it to try tracing it back again.  

I still can't find anything wrong

**Comment by SlimAhmad** [comment]
@glhays could it be a bug on github or probably, I'm missing something?

**Comment by glhays** [comment]
We can just leave this open, and keep an eye on it. Not sure what it is.

> [@glhays](https://github.com/glhays) could it be a bug on github or probably, I'm missing something?
